# Generated by Django 3.2.7 on 2021-10-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Guest', max_length=250, verbose_name='имя пользователя'),
        ),
    ]
